; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; maxgerhardt의 bluepad32 전용 아두이노 프레임워크 패키지만 사용합니다.
platform_packages = 
    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip

; 기존 필터들은 원래대로 깔끔하게 복구합니다.
build_src_filter = +<*> -<.git/> -<.svn/> -<examples/> -<tests/>

lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.1
    ; 중복 충돌을 일으키던 ricardoquesada/bluepad32 깃허브 주소를 여기서 완전히 지웠어!